name: GitHub Hosted Runner SSH Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Update package list
        if: always()
        continue-on-error: true
        run: |
          sudo apt-get update

      - name: Install dependencies
        if: always()
        continue-on-error: true
        run: |
          sudo apt-get install -y curl

      - name: Set root password
        if: always()
        continue-on-error: true
        run: |
          echo "root:root" | sudo chpasswd

      - name: Create root home directory and data folder with permissions
        if: always()
        continue-on-error: true
        run: |
          sudo mkdir -p /root
          sudo chown root:root /root
          sudo chmod 755 /root
          sudo mkdir -p /root/data
          sudo chown root:root /root/data
          sudo chmod 777 /root/data

      - name: Restore /root/data cache
        if: always()
        continue-on-error: true
        uses: actions/cache@v3
        id: cache-restore
        with:
          path: /root/data
          key: ${{ runner.os }}-data-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-data-

      - name: Start sshx.io terminal
        if: always()
        continue-on-error: true
        timeout-minutes: 350
        run: |
          curl -sSf https://sshx.io/get | sh -s run

      - name: Save /root/data cache
        if: always()
        continue-on-error: true
        uses: actions/cache@v3
        with:
          path: /root/data
          key: ${{ runner.os }}-data-${{ hashFiles('**/lockfile') }}
